AWSTemplateFormatVersion : '2010-09-09'
Transform: AWS::Serverless-2016-10-31
Resources:
  BackendLambdaFunction:
    Type: AWS::Serverless::Function
    Properties:
      Runtime: python3.6
      CodeUri: ./backend_lambda
      Handler: backend_lambda.handler
      Events:
        GetEvent:
          Type: Api
          Properties:
            Path: /
            Method: GET
Outputs:
  ApiUrl:
    Value: !Join
      - ''
      - - https://
        - !Ref ServerlessRestApi
        - '.execute-api.'
        - !Ref 'AWS::Region'
        - '.amazonaws.com/'
        - !Ref ServerlessRestApiProdStage
